# Generated by Django 4.2.7 on 2023-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lclt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
